name: Docker Image CI

on:
  push:
    branches:
    - dev

jobs:

  build:
    name: build latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eliearnaud/metashark:latest-dev
    - uses: docker/build-push-action@v2
    - name: Push the Docker image
      run: docker push eliearnaud/metashark:latest-dev
